'use strict';
let state=null,tab='overview';
const $=s=>document.querySelector(s);
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n;}
const money=v=>Number(v).toLocaleString('en-US',{style:'currency',currency:'USD'});
const pct=v=>(Number(v)*100).toFixed(2)+'%';
function badge(text){return el('span',text,'badge '+(/fail|halt/.test(text)?'error':/historical|pending|review|inconclusive/.test(text)?'warn':''));}
function section(title){const s=el('section',undefined,'panel');s.append(el('h2',title));return s;}
function button(text,fn){const b=el('button',text,'link');b.onclick=fn;return b;}
function table(headers,rows){const wrap=el('div',undefined,'scroll'),t=el('table'),head=el('thead'),r=el('tr');headers.forEach(h=>r.append(el('th',h)));head.append(r);t.append(head);const body=el('tbody');rows.forEach(row=>{const tr=el('tr');row.forEach(v=>{const td=el('td');if(v instanceof Node)td.append(v);else td.textContent=String(v??'—');tr.append(td);});body.append(tr);});t.append(body);wrap.append(t);return wrap;}
function details(title,body){$('#detail-title').textContent=title;$('#detail-content').replaceChildren(body);$('#detail').showModal();}
function jsonView(value){return el('pre',JSON.stringify(value,null,2));}
function stats(account){const s=el('div',undefined,'stats'),m=account?.summary;[['Paper equity',m?money(m.final_equity):'—'],['Cash',m?money(m.ending_cash):'—'],['Units held',m?m.ending_quantity:'—'],['Queued jobs',state.jobs.filter(j=>j.state==='pending').length]].forEach(([label,value])=>{const d=el('div',undefined,'stat');d.append(el('span',label),el('strong',value));s.append(d);});return s;}
function portfolioPanel(){const s=section('Paper portfolios'),f=el('div',undefined,'filters'),search=el('input'),strategy=el('select'),status=el('select'),results=el('div');search.placeholder='Search name or symbol';search.setAttribute('aria-label','Search portfolios');strategy.setAttribute('aria-label','Filter strategy');status.setAttribute('aria-label','Filter status');[['All strategies',''],...Array.from(new Set(state.portfolios.map(p=>p.spec.strategy))).map(x=>[x,x])].forEach(([t,v])=>{const o=el('option',t);o.value=v;strategy.append(o);});[['All statuses',''],['Active','active'],['Paused','paused']].forEach(([t,v])=>{const o=el('option',t);o.value=v;status.append(o);});
const update=()=>{const list=state.portfolios.filter(p=>(p.id+' '+p.spec.symbol).toLowerCase().includes(search.value.toLowerCase())&&(!strategy.value||strategy.value===p.spec.strategy)&&(!status.value||status.value===p.status));results.replaceChildren(list.length?table(['Name','Symbol','Strategy','Through','Equity','Status'],list.map(p=>[button(p.id,()=>openPortfolio(p.id)),p.spec.symbol,p.spec.strategy,p.summary.through,money(p.summary.final_equity),badge(p.summary.risk_halted?'risk halted':p.status)])):el('p','No portfolios match these filters.','empty'));};[search,strategy,status].forEach(n=>n.oninput=update);f.append(search,strategy,status);s.append(f,results,el('p','Each row is an independent account. Balances are not pooled. Open an account to inspect fills and risk rules.','helper'));update();return s;}
function health(account){const s=section('Data health'),dl=el('dl');[['Latest account session',account?.summary.through??'No account'],['Calendar coverage','2025–2026'],['Source',account?.spec.kind==='vendor_checked_engineering_only'?'Checked vendor snapshot':(account?.spec.kind??'No snapshot')],['Account mode',account?.spec.historical?'Historical replay':'Forward paper'],['Execution','Simulated next open']].forEach(([a,b])=>{const d=el('div');d.append(el('dt',a),el('dd',b));dl.append(d);});s.append(dl,el('p','Historical accounts are demonstrations, not current market monitoring. Forward updates reject stale data and revised history.','helper'));return s;}
function experiments(limit=3){const s=section('Recent experiments');s.append(state.experiments.length?table(['Experiment','Type','Evidence'],state.experiments.slice(0,limit).map(e=>{const a=el('a','Open report','link');a.href=e.url;a.target='_blank';a.rel='noopener';return [e.id,({'synthetic_bootstrap_calibration':'Synthetic calibration','rolling_selection_independent_fold_diagnostic':'Walk-forward diagnostic','fixed_rule_chronological_diagnostic':'Chronological diagnostic','backtest':'Backtest'}[e.kind]??e.kind),a];})):el('p','No reports saved yet. Run walk-forward or calibrate from the CLI.','empty'));s.append(el('p','Reports include historical experiments from earlier code versions. Read their source identity and limitations before comparing results.','helper'));return s;}
function jobs(){const s=section('Background jobs');s.append(state.jobs.length?table(['Job','Type','Status','Next due / last finish','Attempts','Details'],state.jobs.map(j=>[j.id.slice(0,10),j.kind,badge(j.state),new Date(j.due*1000).toLocaleString(),j.attempts,button('Inspect',()=>details('Job '+j.id,jsonView(j)))])):el('p','No background jobs queued.','empty'));s.append(el('p','Python runs numerical jobs without AI usage. Pausing prevents future claims; an already running computation may finish. Use job-add, job-pause and job-resume in the CLI.','helper'));return s;}
function research(){const s=section('AI research review');s.append(el('p','Codex produces research suggestions and critiques. Model text cannot place orders, change risk settings or promote a strategy.','helper'));s.append(state.research.length?table(['Request','Role','Status','Created','Review'],state.research.map(r=>[r.request.question.slice(0,65),r.request.role,badge(r.state),r.created.slice(0,10),button('Open',()=>{const b=el('div');b.append(el('h3','Question'),el('p',r.request.question));if(r.response){b.append(el('h3','Untrusted model response'),el('p',r.response.summary));['hypotheses','concerns','suggested_experiments'].forEach(k=>{b.append(el('h3',k.replaceAll('_',' ')));const list=el('ul');r.response[k].forEach(x=>list.append(el('li',x)));b.append(list);});}else b.append(el('p','Awaiting a response. Export to your existing Codex session, then import the response.'));const d=el('details');d.append(el('summary','Frozen request and evidence'),jsonView(r.request));b.append(d);details('Research review',b);})])):el('p','No research requests. Use research-submit to attach deterministic evidence.','empty'));return s;}
function events(){const s=section('Activity log');s.append(state.events.length?table(['Time (UTC)','Event','Subject'],state.events.slice(0,20).map(e=>[e.time,e.kind,e.subject])):el('p','No recorded activity.','empty'));return s;}
function chart(points){const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 850 180');svg.classList.add('chart');svg.setAttribute('role','img');svg.setAttribute('aria-label','Equity at each completed session; display scale auto-fits the account');const values=points.map(p=>Number(p.equity)),lo=Math.min(...values),hi=Math.max(...values),span=hi-lo||1;const line=document.createElementNS(ns,'polyline');line.setAttribute('points',values.map((v,i)=>`${65+i*765/Math.max(1,values.length-1)},${140-(v-lo)*115/span}`).join(' '));svg.append(line);[[5,20,money(hi)],[5,145,money(lo)],[65,175,points[0].date],[740,175,points.at(-1).date]].forEach(([x,y,t])=>{const label=document.createElementNS(ns,'text');label.setAttribute('x',x);label.setAttribute('y',y);label.classList.add('chart-label');label.textContent=t;svg.append(label);});return svg;}
async function openPortfolio(id){try{const r=await fetch('/api/portfolio?id='+encodeURIComponent(id));if(!r.ok)throw Error('Portfolio unavailable');const p=await r.json(),b=el('div');b.append(badge(p.spec.historical?'Historical replay':'Forward paper'),el('p',`${p.spec.symbol} · ${p.spec.strategy} · revision ${p.revision} · through ${p.summary.through}`),stats(p),chart(p.result.equity),el('p',`Return ${pct(p.summary.total_return)} · Maximum drawdown ${pct(p.summary.max_drawdown)} · Fees ${money(p.summary.fees_paid)} · Receivables ${money(p.summary.ending_dividend_receivable)}`),el('h3','Simulated fills'));
b.append(p.result.fills.length?table(['Signal','Fill','Side','Units','Price','Fee','Cash'],p.result.fills.map(f=>[f.signal_date,f.date,f.action,f.quantity,f.price,f.fee,f.cash_after])):el('p','No fills in this account.'));b.append(el('h3','Risk and execution rules'),jsonView(p.spec),el('h3','Pending signal'),jsonView(p.result.pending),el('h3','Rejected orders'),jsonView(p.result.rejections));details(p.id,b);}catch(e){showError(e);}}
function render(){const c=$('#content');c.replaceChildren();document.querySelectorAll('nav button').forEach(b=>{if(b.dataset.tab===tab)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});const titles={overview:['Research overview','Accounts, evidence and background activity in one place.'],portfolios:['Paper portfolios','Independent simulated accounts with replayable ledgers.'],jobs:['Background jobs','Durable schedules, retries and execution history.'],research:['Research review','Read model suggestions alongside their frozen evidence.'],experiments:['Experiment library','Inspect the assumptions behind each result.']};$('#heading').textContent=titles[tab][0];$('#subtitle').textContent=titles[tab][1];const a=state.portfolios[0];$('#notice').textContent=(a?.spec.historical?'Historical demonstration data. ':'')+'Paper simulation only. No live orders. Research results do not establish profitability.';if(tab==='overview'){c.append(stats(a));if(state.portfolios.length>1)c.append(el('p','Metrics above: '+a.id+' only.','helper'));const grid=el('div',undefined,'grid');grid.append(portfolioPanel(),health(a));c.append(grid,experiments(),jobs());}else if(tab==='portfolios')c.append(portfolioPanel());else if(tab==='jobs')c.append(jobs(),events());else if(tab==='research')c.append(research());else c.append(experiments(state.experiments.length));}
function showError(e){$('#error').hidden=false;$('#error').textContent='Unable to load current state: '+e.message;}
async function refresh(){const b=$('#refresh');b.disabled=true;try{const r=await fetch('/api/state');if(!r.ok)throw Error('Server returned '+r.status);state=await r.json();$('#error').hidden=true;$('#updated').textContent='Updated '+new Date(state.server_time).toLocaleTimeString();render();}catch(e){showError(e);}finally{b.disabled=false;}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;if(state)render();});$('#refresh').onclick=refresh;$('#close-detail').onclick=()=>$('#detail').close();refresh();
